vagrant:
  base_box: servtag-test08
  hosts_file: './hosts'
  vagrant_file: '/home/bendyk/vagrant_tests/Vagrantfile'
  ip_mem: '/home/bendyk/ip_mem'
  management_path: '/home/bendyk/dealomio_management_api'
  targeting_path: '/home/bendyk/dealomio_targeting_api'
  dealkeeper_path: '/home/bendyk/dealomio_dealkeeper'
